### ISSUE TITLE
nokogiri installation error in ubuntu

### ISSUE THREAD

**Issue by deep12650** [FarmBot/Farmbot-Web-App#1739]
I am using vagrant and Virtual Box VM in MAC OS CATALINA. I couldn't able to figure why is this error coming. I have already install build-essential, patch ruby-dev, zlib1g-dev, liblzma-dev, libxml2-dev, libxslt1-dev, libgmp-dev. 

# System Information
```
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              1
On-line CPU(s) list: 0
Thread(s) per core:  1
Core(s) per socket:  1
Socket(s):           1
NUMA node(s):        1
Vendor ID:           GenuineIntel
CPU family:          6
Model:               142
Model name:          Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
Stepping:            10
CPU MHz:             1392.000
BogoMIPS:            2784.00
Hypervisor vendor:   KVM
Virtualization type: full
L1d cache:           32K
L1i cache:           32K
L2 cache:            256K
L3 cache:            6144K
NUMA node0 CPU(s):   0
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid tsc_known_freq pni pclmulqdq monitor ssse3 cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single pti fsgsbase avx2 invpcid rdseed clflushopt md_clear flush_l1d
```

# Log Result
```
Fetching nokogiri 1.10.8
Installing nokogiri 1.10.8 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /bundle/ruby/2.6.0/gems/nokogiri-1.10.8/ext/nokogiri
/usr/local/bin/ruby -I /usr/local/lib/ruby/2.6.0 -r ./siteconf20200323-1-1i4ql02.rb extconf.rb
checking if the C compiler accepts ... yes
Building nokogiri using packaged libraries.
Using mini_portile version 2.4.0
checking for gzdopen() in -lz... yes
checking for iconv... yes
************************************************************************
IMPORTANT NOTICE:

Building Nokogiri with a packaged version of libxml2-2.9.10
with the following patches applied:
	- 0001-Revert-Do-not-URI-escape-in-server-side-includes.patch
	- 0002-Remove-script-macro-support.patch
	- 0003-Update-entities-to-remove-handling-of-ssi.patch
	- 0004-libxml2.la-is-in-top_builddir.patch
	- 0005-Fix-infinite-loop-in-xmlStringLenDecodeEntities.patch

Team Nokogiri will keep on doing their best to provide security
updates in a timely manner, but if this is a concern for you and want
to use the system library instead; abort this installation process and
reinstall nokogiri as follows:

    gem install nokogiri -- --use-system-libraries
        [--with-xml2-config=/path/to/xml2-config]
        [--with-xslt-config=/path/to/xslt-config]

If you are using Bundler, tell it to use the option:

    bundle config build.nokogiri --use-system-libraries
    bundle install

Note, however, that nokogiri is not fully compatible with arbitrary
versions of libxml2 provided by OS/package vendors.
************************************************************************
Extracting libxml2-2.9.10.tar.gz into tmp/x86_64-pc-linux-gnu/ports/libxml2/2.9.10... ERROR, review
'/bundle/ruby/2.6.0/gems/nokogiri-1.10.8/ext/nokogiri/tmp/x86_64-pc-linux-gnu/ports/libxml2/2.9.10/extract.log' to see what happened. Last lines are:
========================================================================
tar: libxml2-2.9.10/test/relaxng/ambig_name-class2.rng: Cannot hard link to 'libxml2-2.9.10/test/relaxng/ambig_name-class.xml': Operation not permitted
tar: libxml2-2.9.10/test/relaxng/ambig_name-class.rng: Cannot hard link to 'libxml2-2.9.10/test/relaxng/tutorA.rng': Operation not permitted
tar: Exiting with failure status due to previous errors
========================================================================
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/usr/local/bin/$(RUBY_BASE_NAME)
	--help
	--clean
	--use-system-libraries
	--enable-static
	--disable-static
	--with-zlib-dir
	--without-zlib-dir
	--with-zlib-include
	--without-zlib-include=${zlib-dir}/include
	--with-zlib-lib
	--without-zlib-lib=${zlib-dir}/lib
	--enable-cross-build
	--disable-cross-build
/bundle/ruby/2.6.0/gems/mini_portile2-2.4.0/lib/mini_portile2/mini_portile.rb:402:in `block in execute': Failed to complete extract task (RuntimeError)
	from /bundle/ruby/2.6.0/gems/mini_portile2-2.4.0/lib/mini_portile2/mini_portile.rb:373:in `chdir'
	from /bundle/ruby/2.6.0/gems/mini_portile2-2.4.0/lib/mini_portile2/mini_portile.rb:373:in `execute'
	from /bundle/ruby/2.6.0/gems/mini_portile2-2.4.0/lib/mini_portile2/mini_portile.rb:367:in `extract_file'
	from /bundle/ruby/2.6.0/gems/mini_portile2-2.4.0/lib/mini_portile2/mini_portile.rb:62:in `block in extract'
	from /bundle/ruby/2.6.0/gems/mini_portile2-2.4.0/lib/mini_portile2/mini_portile.rb:60:in `each'
	from /bundle/ruby/2.6.0/gems/mini_portile2-2.4.0/lib/mini_portile2/mini_portile.rb:60:in `extract'
	from /bundle/ruby/2.6.0/gems/mini_portile2-2.4.0/lib/mini_portile2/mini_portile.rb:151:in `cook'
	from extconf.rb:365:in `block (2 levels) in process_recipe'
	from extconf.rb:257:in `block in chdir_for_build'
	from extconf.rb:256:in `chdir'
	from extconf.rb:256:in `chdir_for_build'
	from extconf.rb:364:in `block in process_recipe'
	from extconf.rb:262:in `tap'
	from extconf.rb:262:in `process_recipe'
	from extconf.rb:557:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /bundle/ruby/2.6.0/extensions/x86_64-linux/2.6.0/nokogiri-1.10.8/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /bundle/ruby/2.6.0/gems/nokogiri-1.10.8 for inspection.
Results logged to /bundle/ruby/2.6.0/extensions/x86_64-linux/2.6.0/nokogiri-1.10.8/gem_make.out

An error occurred while installing nokogiri (1.10.8), and Bundler cannot continue.
Make sure that `gem install nokogiri -v '1.10.8' --source 'https://rubygems.org/'` succeeds before bundling.

In Gemfile:
  valid_url was resolved to 0.0.4, which depends on
    rails was resolved to 6.0.2.1, which depends on
      actioncable was resolved to 6.0.2.1, which depends on
        actionpack was resolved to 6.0.2.1, which depends on
          actionview was resolved to 6.0.2.1, which depends on
            rails-dom-testing was resolved to 2.0.3, which depends on
              nokogiri

```
# Steps to Reproduce
`sudo docker-compose run web bundle install`

# Results of `git log -1`
```
commit bda30bae09fdb544f9eb6dff529f1b90d4adcb82 (HEAD -> master, origin/master)
Merge: 8630718 149451c
Author: Rick Carlino <RickCarlino@users.noreply.github.com>
Date:   Wed Mar 18 16:23:53 2020 -0500

    Merge pull request #1736 from FarmBot/staging

    v9.2.3 - Jolly Juniper
```

**Comment by RickCarlino** [comment]
@deep12650

The only platform that FarmBot, Inc supports is `Ubuntu x86_64` via `docker-compose` so I cannot provide you any support on the matter. If anyone in the community has experience with this, help would be appreciated. In the meantime I am going to close the issue because I can't spend any time investigating the matter.

**Comment by RickCarlino** [comment]
Additionally, it may be worth raising an issue with Nokogiri directly, or possibly asking the question again on a more general Q&A site such as StackOverflow. I QAed the `ubuntu_example.sh` on a fresh install of Ubuntu 20 last Friday, so it is unlikely that there is a problem with the FarmBot Web App itself.
