### ISSUE TITLE
How can I change http://local:8080 to http://local:80

### ISSUE THREAD

**Issue by Arduns** [FarmBot/Farmbot-Web-App#335]
How can I change http://local:8080 to http://local:80

with use 8080 the pi3 cloud not contect to the server

MQTT Q:
AUTH START
Will fetch certificate...
Did fetch certificate. Will verify token with certificate.
AUTH FAIL sk__2@163.com
jwt malformed
{ Error
    at Object.module.exports [as verify] (/home/ardun/mqtt/node_modules/jsonwebtoken/verify.js:54:17)
    at ok (/home/ardun/mqtt/app/security/verify_token.js:24:20)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7) name: 'JsonWebTokenError', message: 'jwt malformed' }
AUTH START
Will fetch certificate...
Did fetch certificate. Will verify token with certificate.
AUTH FAIL sk__2@163.com
jwt malformed
{ Error
    at Object.module.exports [as verify] (/home/ardun/mqtt/node_modules/jsonwebtoken/verify.js:54:17)
    at ok (/home/ardun/mqtt/app/security/verify_token.js:24:20)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7) name: 'JsonWebTokenError', message: 'jwt malformed' }

**Comment by RickCarlino** [comment]
@Arduns A lot has changed in the past few days with how the server is built. You may need to run an update.

Try this:

```
git pull origin master
yarn install
bundle install
./install_frontend.sh
sudo PORT=80 rails s -b 0.0.0.0
```

You will need `sudo` to run on port 80 on most Linux machines.

Please let me know if that does not work. A lot has changed in the last week, so I appreciate the bug reports.

**Comment by Arduns** [comment]
@RickCarlino  thanks for help I have git a new version in 6 hour ago.  and I have fix it 
![wechatimg14309](https://user-images.githubusercontent.com/10508878/27918633-235c3666-62a2-11e7-9929-ef6d59d4749b.jpeg)

and use this link to fix the last error and  the Farmbot-Web-App work 

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/17581/files#diff-96b72df8b13a8a590e4f160cbc51f40c
