### ISSUE TITLE
ubuntu provedure npm test

### ISSUE THREAD

**Issue by nicmel** [FarmBot/Farmbot-Web-App#635]
# Expected Behavior

no errors during test

# Actual Behavior

error during test:

webpack/farm_designer/farm_events/__tests__/edit_fe_form_test.tsx (5.262s)
  <FarmEventForm/> › Recombines local state back into a Partial<TaggedFarmEvent["body"]>
   expect(string).toContain(value)
     Expected string:
      "2017-07-31T08:35:00.000Z"
    To contain value:
      "2017-08-01"
      
      at Object.<anonymous> (webpack/farm_designer/farm_events/__tests__/edit_fe_form_test.tsx:153:31)
          at new Promise (<anonymous>)
          at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

# Steps to Reproduce

following the install procedure on ubuntu server

**Comment by RickCarlino** [comment]
@nicmel This is likely a timezone adjustment issue on your local machine.

You can safely ignore it (for now).

I will leave this issue open until a fix is deployed. Thanks for letting us know.
