### ISSUE TITLE
Installation Failure

### ISSUE THREAD

**Issue by Darchevil** [FarmBot/Farmbot-Web-App#673]
# Expected Behavior
Test successful when launching RAILS_ENV=test rake db:create db:migrate && rspec spec

# Actual Behavior
I have got 10 failures but it's the same failure than 1)
Failures:

  1) Api::SequencesController#create tracks Points
     Failure/Error: tid = FactoryBot.create(:tool, device: device).id
     
     NoMethodError:
       undefined method `pullout_direction' for #<Tool:0x00000000087a73c8>
     # /usr/share/rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
     # ./spec/stuff.rb:36:in `sequence_body_for'
     # ./spec/controllers/api/sequences/sequences_create_spec.rb:201:in `block (3 levels) in <top (required)>'

Failed examples:

rspec ./spec/controllers/api/sequences/sequences_create_spec.rb:191 # Api::SequencesController#create tracks Points

rspec ./spec/controllers/api/sequences/sequences_create_spec.rb:15 # Api::SequencesController#create handles a well formed AST in the body attribute

rspec ./spec/controllers/api/sequences/sequences_create_spec.rb:58 # Api::SequencesController#create tracks SequenceDependency

rspec ./spec/controllers/api/sequences/sequences_create_spec.rb:27 # Api::SequencesController#create disregards extra attrs (like `uuid`) on sequence body nodes

rspec ./spec/controllers/api/tools/destroy_spec.rb:66 # Api::ToolsController#destroy does not destroy a tool when in a slot

rspec ./spec/controllers/api/tools/destroy_spec.rb:24 # Api::ToolsController#destroy does not destroy a tool when in use by a sequence

rspec ./spec/controllers/api/tools/destroy_spec.rb:14 # Api::ToolsController#destroy destroy a tool

rspec ./spec/controllers/api/sequences/sequences_update_spec.rb:24 # Api::SequencesController#update refreshes sequence dependencies on update

rspec ./spec/controllers/api/tools/show_spec.rb:12 # Api::ToolsController#show renders a tool
rspec ./spec/controllers/api/points/destroy_spec.rb:40 # Api::PointsController#destroy deletes a plant

# Steps to Reproduce

**Comment by RickCarlino** [comment]
@Darchevil Thanks for the detailed information!

It looks like your local database is running an outdated schema. Running `RAILS_ENV=test rails db:reset` might help.

It would be helpful to see the exact version of the web app that you're running. Can you please copy/paste the results of this command?:

```
git log -1
```

**Comment by Darchevil** [comment]
Hey Rick ! 

Thanks for your message. This is my git log -1 result : 

darchevil@yoann-BM:~/FWA/Farmbot-Web-App$ git log -1
commit 69f565600527e12700b6dd1408a625301de06da8
Merge: c9ea068 ee511d3
Author: Rick Carlino <RickCarlino@users.noreply.github.com>
Date:   Mon Jan 22 10:26:39 2018 -0600

    Merge pull request #632 from RickCarlino/staging
    
    v6.1.0 - Gracious Guava

Is it good ? 
Thank you again !
